FROM ubuntu:trusty

RUN apt-get update \
    && apt-get install -y git redis-server libboost1.55-all-dev nodejs-dev nodejs-legacy npm cmake libssl-dev

RUN git clone https://github.com/clintar/cryptonote-xmr-pool.git pool && cd pool \
    && git checkout d724f60768f09fa9ed84e6444f94585edec9fe33 \
    && npm update

COPY pool-config.json /pool/config.json

WORKDIR /pool

EXPOSE 3333 5555 7777 8888 8117

ENTRYPOINT ["/usr/bin/node"]

CMD ["init.js"]
