FROM ubuntu:16.04

RUN apt-get update \
    && apt-get install -y wget bzip2

WORKDIR monero

RUN wget https://downloads.getmonero.org/cli/linux64 \
    && tar --strip-components=2 -xf /monero/linux64 \
    && rm linux64

RUN cp monerod /usr/local/bin/

VOLUME /monero/.bitmonero

EXPOSE 18081

ENTRYPOINT ["monerod"]

CMD ["--confirm-external-bind", "--rpc-bind-ip", "0.0.0.0", "--data-dir", "/monero/.bitmonero"]
